name: Java CI

on:
  push:
    branches:
      - main
      - develop
      
jobs:
  maven_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - run: mvn --batch-mode --update-snapshots verify
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
      - name: 'Upload .jar'
        uses: actions/upload-artifact@v2.2.4
        with:
          name: jar
          path: ./target/*.jar
  
  release-content:
    name: 'Create GitHub Release'
    runs-on: ubuntu-latest
    needs: [ maven_build ]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    steps:      
      - name: 'Download Artifacts'
        uses: actions/download-artifact@v2.0.10
        with:
          name: app.jar
      - name: 'Create GitHub Release'
        uses: softprops/action-gh-release@v1
        with:
          files: ./**/*.jar         
          tag_name: v${{ github.run_number }}
          name: Release V${{ github.run_number }}
